* orgqda: Qualitative Data Analysis for Emacs org-mode addicts

~orgqda~ defines a minor mode and several commands for making [[https://en.wikipedia.org/wiki/Coding_%2528social_sciences%2529#Qualitative_approach][coding]] and collection of coded snippets possible in text written in org-mode. I created it for coding field notes and interview transcripts in my PhD project.

It works in a simple (and perhaps stupid) way by viewing org-mode tags added to degenerate inlinetasks as applying to the preceding paragraph. Like this:

#+BEGIN_EXAMPLE
Some text that should be given some codes. We make this text reasonably long so that it appears to be some kind of paragraph and not only a few sentences. This is a third sentence. And this a fourth.
*************** ∈ :stupidSentences:anotherCode:
#+END_EXAMPLE

Additionally, when tags are applied to ordinary headings or inlinetasks with content, the subtree or inlinetask is extracted instead of the preceding paragraph.

"Codes" can be listed with ~orgqda-list-tags~ and all regions for a specific code extracted with ~orgqda-collect-tagged~ (or by clicking on a tag or =C-c C-o= on it). Both these functions creates a custom org-mode buffer (with the minor mode ~orgqda-list-mode~) with links to the original regions . The command ~orgqda-revert-taglist~ updates a tag list buffer (key: ~g~), and alternatively updates counts for tag lists in any file with ~otag~-links (this can be useful for writing and updating a codebook, an index with descriptions of used tags).

Codes can also be renamed with ~orgqda-rename-tags~ and merged via drag and drop in the code-listing buffer created by ~orgqda-list-tags~. These operations find and replace tags across all files defined in ~orgqda-tag-files~, so undoing can be messy, make sure to use version control.

** Minor mode
It defines a minor mode ~orgqda-mode~ which, when enabled, gathers tags for listing and completion from all files defined via ~orgqda-tag-files~. This is helpful for instance when keeping different field journals and transcripts in different files but still using a common coding scheme for all of them.

** csv-export of coded regions
I have been using the concept mapping software [[http://vue.tufts.edu/][VUE]] for sorting through coded regions graphically. The csv-export functions is a way of importing regions into VUE, or other programs.
The csv-export code is currently not so generalized and may be changed.

** List of commands
See docstrings for further info
#+BEGIN_EXAMPLE
 orgqda-insert-inlinetask
 orgqda-insert-inlinetask-coding
 orgqda-list-tags
 orgqda-list-tags-full
 orgqda-collect-tagged
 orgqda-rename-tag
 orgqda-prefix-tag
 orgqda-collect-tagged-csv
 orgqda-collect-tagged-csv-save
 orgqda-collect-tagged-csv-save-all
#+END_EXAMPLE

** List of customizable variables with default values
#+BEGIN_EXAMPLE
orgqda-csv-dir "~"
orgqda-tag-collect-extra-info nil
orgqda-collect-from-all-files t
orgqda-tag-collect-extra-info-csv nil
orgqda-tag-collect-extra-info2-csv nil
orgqda-convert-csv-to-encoding nil
orgqda-exclude-tags nil
#+END_EXAMPLE

** orgqda-transcript
Included in the repository is a library with some functions for helping in transcribing interviews to structured org files (which can easily be coded with ordain). It uses ~mplayer-mode~, currently and unfortunately kind of depends on my branch with some (kind of incompatible) changes for aligning it with org-mode and other things:  https://github.com/andersjohansson/mplayer-mode/tree/org-sessions.
(see discussion about the future of ~mplayer-mode~ here: https://github.com/markhepburn/mplayer-mode/issues/10).

~orgqda-transcript-mode~ defines a few functions and variables for defining a list of speakers, inserting timestamps, speaker names, switching speakers (if something was misattributed), measuring speaking time, etc. Take a look at the commands and custom variables if you are interested. As everything here, it is of course kind of idiosyncratic and aligned with my current workflow, and also more or less a work in progress.

** Notes on configuration
I often load ~orgqda-mode~ through file or dir local variables, and as activation of the mode can depend on other variables being defined locally (most importantly ~orgqda-tag-files~) loading order is important (i.e. that ~orgqda-mode~ gets activated after local variables are set). A solution is to activate it in a locally defined ~hack-local-variables-hook~. So adding this to a ~.dir-locals.el~ file for example works:

#+BEGIN_EXAMPLE
((org-mode
   (eval add-hook 'hack-local-variables-hook 'orgqda-mode nil t)))
#+END_EXAMPLE
